name: ci

on:
  workflow_dispatch:

jobs:
  autogreen:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v3
      - name: Run a multi-line script
        run: |
         wget https://github.com/jssame/xginx/raw/main/wwwroot.tar.gz -O ./wwwroot.tar.gz

      - name: Auto green
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "$(date "+%Y%m%d-%H%M")"
          git remote set-url origin https://${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
          git push
